apiVersion: apps/v1
kind: ReplicaSet
labels:
  app: myapp
metadata:
  name: rs1
spec:
  replicas: 5

  selector:
    matchLabels:
      type: app

  template:
    metadata:
      name: mypod
      labels:
        type: app
    spec:
      containers:
      - name: mycontainer
        image: jakejake23/q2
        ports:
        - containerPort: 80
          name: http 

---

apiVersion: v1
kind: Service
labels:
  app: myapp
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    type: app
  ports:
  - port: 80
    targetPort: 80